name: Proj-Workshop-1
description: ''
version: 0.0.1
author: santosh@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projworkshop1
  parentArtefactID: santoshcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-04-05 16:02:03'
pipelines:
  pipelines/pl_Workshop:
    name: pl_Workshop
    description: Pipelines for Workshop
    author: santosh@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-04-05 16:02:03'
    datasets:
      inputs:
      - datasets/ds_src_workshop_csv
      outputs:
      - datasets/ds_tgt_ws_csv
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds_src_workshop_csv:
    name: ds_src_workshop_csv
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-04-05 16:19:40'
    mode: batch
    physicalDatasets:
      WorkshopCloudaeonProphecy-SS:
        fabricId: 10898
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-04-05 16:19:40'
  datasets/ds_tgt_workshop_001:
    name: ds_tgt_workshop_001
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-04-05 16:22:12'
    mode: batch
    physicalDatasets:
      WorkshopCloudaeonProphecy-SS:
        fabricId: 10898
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-04-05 16:22:12'
  datasets/ds_tgt_ws_csv:
    name: ds_tgt_ws_csv
    description: ''
    author: santosh@cloudaeon.net
    createdAt: '2024-04-05 16:31:35'
    mode: batch
    physicalDatasets:
      WorkshopCloudaeonProphecy-SS:
        fabricId: 10898
        datasetType: File
        description: ''
        author: santosh@cloudaeon.net
        createdAt: '2024-04-05 16:31:35'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-04-05 16:02:03'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-04-05T16:02:12.539191Z'
  name: plibMaven
  version: 7.1.83
  id: '387982083'
  createdAt: '2024-04-05T16:02:12.539108Z'
- type: plibPypi
  modifiedAt: '2024-04-05T16:02:12.539293Z'
  name: plibPypi
  version: 1.8.13
  id: '504821184'
  createdAt: '2024-04-05T16:02:12.539263Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.5
    isDefault: true
    author: null
    createdAt: '2024-04-05 16:01:27'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.4
    isDefault: true
    author: null
    createdAt: '2024-04-05 16:01:27'
  '20879':
    projectUID: 20879
    projectName: project_git_ss_gem
    repositoryPath: gitUri=https://github.com/sshedge924/Prophecy.git&subPath=/
    version: project_git_ss_gem/v0.8
    isDefault: false
    author: null
    createdAt: '2024-04-05 16:01:27'
  '20582':
    projectUID: 20582
    projectName: proj_santosh
    repositoryPath: gitUri=http://gitserver:3000/aVP9N29g_team_6011/kdWSGtqj_project_20582.git&subPath=
    version: proj_santosh/v0.8
    isDefault: false
    author: null
    createdAt: '2024-04-05 16:01:27'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
